### ISSUE TITLE
数据重置和后台图标显示bug

### ISSUE THREAD

**Issue by itthinker1** [Gourds/WebStackLaravel#10]
首先感谢作者制作了“WebStackLaravel项目创建的Docker部署版本”，我在使用中发现了2个小bug：

1. 从后台修改内容后，第二次运行 **docker-compose up**时，数据重置了~！然后我注意到了GitHub上的描述：

    > 当只想启动数据库，不进行初始化的话，需要修改`docker-compose.yml`文件中的`command`指令

    ```
    #修改前
    command: ['/entrypoint.sh','new-server']
    #修改后
    command: ['/entrypoint.sh','serve']
    ```

    可是，如果按照这样修改启动docker后会有报错提示，无法访问网站，我试着对/entrypoint.sh做了修改：

    ```sh
    if [ $# -eq 1 ];then
        if [ $1 == 'serve' ];then
            php artisan key:generate   #增加了这一句
            php artisan serve --host=0.0.0.0 --port=8000

    ```

    如此以来，就可以正常运行了~

2. 默认情况下，在admin后台各站点图标无法加载，分析后发现是路径不对，进入镜像内部修改 /opt/navi/.env

   第6行：

   ```
   修改前：APP_URL= localhost
   修改后：APP_URL=
   ```

   

再次感谢作者为开源所做的付出，希望能修复bug，帮助更多的人

**Comment by Gourds** [comment]
@itthinker1 已修改
