### ISSUE TITLE
docker-compose.yml 请在仓库中下载，release file 中打包的还是老文件

### ISSUE THREAD

**Issue by valuex** [Gourds/WebStackLaravel#12]
项目仓库中的`docker-compose.yml`的文件，这个配置是正确的，能正常启动WebStack 容器
![image](https://user-images.githubusercontent.com/3627812/147397684-38f259b9-472f-49e6-8047-5b54b542d302.png)

release file 中的`docker-compose.yml`打包的还是老文件，如下配置并未修改，导致WebStack 容器启动不了报错
`Usage:/entrypoint. sh server regress generate debug`

请刷新下release file 中的`docker-compose.yml`文件

**Comment by Gourds** [comment]
已经处理了
