### ISSUE TITLE
怎么更改环境配置呢?

### ISSUE THREAD

**Issue by SoulGolf** [Gourds/WebStackLaravel#3]
现在启动成功发现host是http://localhost，导致图片全部加载失败了

**Comment by Gourds** [comment]
@SANSANSANl ，是使用docker-compose么？

**Comment by SoulGolf** [comment]
@Gourds 是阿

**Comment by Gourds** [comment]
不应该啊，启动脚本命令是`php artisan serve --host=0.0.0.0 --port=8000`这个，应该不会监听localhost，你访问地址加端口了么，我默认映射的8000

**Comment by SoulGolf** [comment]
@Gourds 打开是没问题，前台能正常访问。就是后台的图片地址都默认跑到http://localhost域名下了。图片都加载不出来，css js域名没问题。

**Comment by Gourds** [comment]
有截图么

**Comment by Gourds** [comment]
先关闭了

**Comment by JackyCZJ** [comment]
同样的问题，尝试在app.php 改了主机名但是还是一样。

**Comment by JackyCZJ** [comment]
需要修改目录下的.env的APP_URL来更改主机地址
