### ISSUE TITLE
群晖里直接 docker 启动失败

### ISSUE THREAD

**Issue by aetherwu** [Gourds/WebStackLaravel#5]
RuntimeException
No application encryption key has been specified.

不知道原因……

**Comment by Gourds** [comment]
是使用docker-compose起的么，启动命令贴一下

**Comment by aetherwu** [comment]
![](http://namecard.dagong.in/1.png)

![](http://namecard.dagong.in/2.png)

![](http://namecard.dagong.in/3.png)

可能是因为它是一种定制的 Docker……
然后……似乎没有命令行。

设置里显示有执行一个命令：
/sbin/tini -- /entrypoint.sh serve

启动后可以看到日志：
PHP 7.2.21 Development Server started at Tue Aug 27 11:57:17 2019
Laravel development server started: <http://0.0.0.0:8000>

求指点……


---

我注意到似乎有一个相关的步骤，但我不知道该怎么整合和修改：

```
Copy .env.example to .env:
cp -a .env.example .env
Generate a key:
php artisan key:generate
```

**Comment by Gourds** [comment]
启动命令用这个
```
/sbin/tini -- /entrypoint.sh new-serve
```
你可以自己搜索一下解决方案，可以参考`https://avnpc.com/pages/use-synology-nas-build-private-cloud`

**Comment by aetherwu** [comment]
我按照网上的办法修改了 Dockerfile。
但镜像本身似乎没有自带mysql，所以配置还不是那么即开即用。
Docker-compose 的群晖用法可能我还要再看看。

From:
```
    && composer install  \
    && cp .env.example .env \
    && chown -R ${RUN_USER}:${RUN_GROUP} ${INSTALL_DIR}\
```

To:
```
    && composer install  \
    && cp .env.example .env \
    && php artisan key:generate \
    && php artisan config:cache \
    && chown -R ${RUN_USER}:${RUN_GROUP} ${INSTALL_DIR}\
```

之后镜像可以顺利启动。之后遭遇 Connection refused 问题（捂脸。

**Comment by ha7rock** [comment]
我也想在群晖上面部署，请问题主，你是否解决了？能否指教一下，谢谢！

**Comment by yuanjh6** [comment]
问题已解决：
问题原因：/entrypoint.sh脚本存在bug，但这个脚本位于镜像里面，所以修改不了，

![image](https://user-images.githubusercontent.com/32973375/99883127-428dbd80-2c60-11eb-8afb-246931870238.png)

图中标1的地方的代码，在第一个if分支也需要，修改下entrypoint.sh脚本即可。
所以切入运行中的容器,修改entrypoint.py脚本，commit容器为image
docker commit wsl webstack-laravel:v1.2.1.2
再修改docker-compose.yml文件，让其加载自己修改后的image即可
我制作的image是yuan886/webstack-laravel:v1.2.1.2
当然，如果想实现自己修改数据库数据后重启依然生效，还需要修改yml的2处，1处/var/lib/mysql(volumns数据映射)，还有一处时
entrypoint.py启动参数，new-server改为serve(不是server)
![image](https://user-images.githubusercontent.com/32973375/99883311-abc20080-2c61-11eb-8c82-84d187e7166f.png)
