### ISSUE TITLE
怎么保存数据啊

### ISSUE THREAD

**Issue by yzddahaoren** [Gourds/WebStackLaravel#6]
目的：能够保存自己记录的一些网址，方便迁移
已经在docker-compose.yml文件加了
`- ./mysql/mysql:/var/lib/mysql`
和
`- ./web/navi:/opt/navi`
了。也复制文件到容器外了
也正常启动了。
可是甚至`docker-compose restart `之后数据就没了。又变成初始的样子了
不了解Laravel应用，怎么能够保存自己记录的网址，方便迁移

**Comment by bobzhanggmail** [comment]
把 command: ['/entrypoint.sh','new-server']里的new-server，改成serve，不然每次数据都会被重新刷掉

**Comment by Gourds** [comment]
@bobzhanggmail 对的，文档也有描述。第一次用new-server启动，之后都用server

**Comment by susttt** [comment]
不能加个是否存在数据的判断吗？
